pull master then rewrite ViewController
DaiSugi01/CryptocurrencyManagement pull request #4
Opened 2021-01-20 22:22 UTC by YukiT1990

conflictsなくなりました。

2021-01-22 02:53 UTC, DaiSugi01 requested changes
修正お願いします。

2021-01-22 02:53 UTC, DaiSugi01 commented on Cryptocurrency Management/ViewController.swift
> +        bt.setTitleColor(UIColor(hex: "#fc0303"), for: .normal)
delete buttonはゴミ箱アイコンにしてください。
```
bt.setImage(UIImage(systemName: "trash"), for: .normal)
bt.tintColor = .red

```

2021-01-22 02:53 UTC, DaiSugi01 commented on Cryptocurrency Management/ViewController.swift
> +        bt.layer.cornerRadius = bt.frame.height * 0.10
0.3くらいの丸みがちょうど良さそうです
`bt.layer.cornerRadius = bt.frame.height * 0.3`

2021-01-22 02:53 UTC, DaiSugi01 commented on Cryptocurrency Management/ViewController.swift
> +        bt.titleLabel?.font = UIFont.systemFont(ofSize: 14)
font sizeは17がいいかもです

2021-01-22 02:53 UTC, DaiSugi01 commented on Cryptocurrency Management/ViewController.swift
>          bt.frame = CGRect(x: 261, y: 76, width: 120, height: 36)
x, yポジションは指定する必要がないので以下に置き換えてください。
（stack viewに入れるので必要なくなる）

delete
`bt.frame = CGRect(x: 261, y: 76, width: 120, height: 36)`
add (radius計算用)
`bt.frame.size.height = 36`

2021-01-22 02:53 UTC, DaiSugi01 commented on Cryptocurrency Management/ViewController.swift
> +        bt.frame = CGRect(x: 16, y: 76, width: 48, height: 48)
x, yポジションは指定する必要がないので以下に置き換えてください。
（stack viewに入れるので必要なくなる）

delete
`bt.frame = CGRect(x: 16, y: 76, width: 48, height: 48)`
add (radius計算用)
`bt.frame.size.width = 48`

2021-01-22 02:53 UTC, DaiSugi01 commented on Cryptocurrency Management/ViewController.swift
> +        bt.layer.cornerRadius = bt.frame.height * 0.50
0.50 -> 0.5

2021-01-22 02:53 UTC, DaiSugi01 commented on Cryptocurrency Management/ViewController.swift
> +        bt.setTitleColor(UIColor(hex: "#fc0303"), for: .normal)
All currencyLabeとedit buttonと delete buttonはconstraintsを管理しやすいようにstack viewに入れてください。

2021-01-22 02:53 UTC, DaiSugi01 commented on Cryptocurrency Management/ViewController.swift
>          view.backgroundColor = UIColor(hex: "#010A43")
readabilityのため、layoutの設定はsetupLayout() functionにまとめてください。

2021-01-22 02:53 UTC, DaiSugi01 commented on Cryptocurrency Management/ViewController.swift
> +            allCurrencyLabel.leadingAnchor.constraint(equalTo: popupView.leadingAnchor, constant: 18)
readabilityのため、layoutの設定はsetupLayout() functionにまとめてください。

2021-01-22 02:53 UTC, DaiSugi01 commented on Cryptocurrency Management/ViewController.swift
> +            addCurrencyButton.heightAnchor.constraint(equalToConstant: 36),
ここは削除して、addCurrencyButtonのconstraintsはwidthAnchorだけ設定してください。

`addCurrencyButton.widthAnchor.constraint(equalToConstant: 140),`

2021-01-22 02:53 UTC, DaiSugi01 commented on Cryptocurrency Management/ViewController.swift
>          bt.backgroundColor = UIColor(hex: "#212A6B", alpha: 1.0)
paddingを入れたいので以下を追加してください。

`bt.titleEdgeInsets = UIEdgeInsets(top: 10, left: 10, bottom: 10, right: 10)`

2021-01-22 02:53 UTC, DaiSugi01 commented on Cryptocurrency Management/ViewController.swift
> +            tableViewSwitchButton.leadingAnchor.constraint(greaterThanOrEqualTo: view.safeAreaLayoutGuide.leadingAnchor, constant: 16),
tableViewSwitchButtonはstack viewに入れると不要になるのでtopとleadingは削除してください

2021-01-22 02:53 UTC, DaiSugi01 commented on Cryptocurrency Management/ViewController.swift
> +            allCurrencyLabel.leadingAnchor.constraint(equalTo: popupView.leadingAnchor, constant: 18)
stack viewに入れると不要になるので削除してください

2021-01-22 02:53 UTC, DaiSugi01 commented on Cryptocurrency Management/ViewController.swift
> +        if allowDissmissModal == true {
allowDissmissModal は truthy valueなので == trueはないほうがいいです。

2021-01-22 02:53 UTC, DaiSugi01 commented on Cryptocurrency Management/ViewController.swift
>              addCurrencyButton.topAnchor.constraint(greaterThanOrEqualTo: view.safeAreaLayoutGuide.topAnchor, constant: 80),
headerSVのconstraintsを追加してください。
topAnchorはsafeAreaLayoutguideから15くらいで（いい感じに調整してください。）

2021-01-22 02:53 UTC, DaiSugi01 commented on Cryptocurrency Management/ViewController.swift
> +        allowDissmissModal = tableViewEditingMode
不要？
後で使いたいなら「currencyTableView.isEditing」が使えるかも？

2021-01-22 02:53 UTC, DaiSugi01 commented on Cryptocurrency Management/ViewController.swift
> +        if tableViewEditingMode == true {
== trueは削除してください

2021-01-22 02:53 UTC, DaiSugi01 commented on Cryptocurrency Management/ViewController.swift
> +    private func layout() {
function名はsetupLayout()のほうがわかりやすそうです

2021-01-22 02:53 UTC, DaiSugi01 commented on Cryptocurrency Management/ViewController.swift
> +        cell.textLabel?.text = registeredCurrencies[indexPath.row].name
ロゴも入れたいのでcellのなかにimageも追加してください

2021-01-22 02:53 UTC, DaiSugi01 commented on Cryptocurrency Management/ViewController.swift
> +        popupView.backgroundColor = UIColor(hex: "#10194E")
popupView（↓）の定義の中で設定してください

    private lazy var popupView: UIView = {
        let view = UIView()
        view.backgroundColor = UIColor(hex: "010A43")
        view.layer.cornerRadius = 20
        return view
    }()

2021-01-22 02:53 UTC, DaiSugi01 commented on Cryptocurrency Management/ViewController.swift
> +        popupView.addSubview(currencyTableView)
popupViewの定義の中で設定してください

2021-01-22 02:53 UTC, DaiSugi01 commented on Cryptocurrency Management/ViewController.swift
> +        currencyTableView.trailingAnchor.constraint(equalTo: popupView.trailingAnchor).isActive = true
constraintsの設定は他の設定と同じところに記載してください

2021-01-22 04:44 UTC, YukiT1990 commented on Cryptocurrency Management/ViewController.swift
> +        bt.setTitleColor(UIColor(hex: "#fc0303"), for: .normal)
修正しました。

2021-01-22 04:44 UTC, YukiT1990 commented on Cryptocurrency Management/ViewController.swift
> +        bt.layer.cornerRadius = bt.frame.height * 0.10
修正しました。

2021-01-22 04:44 UTC, YukiT1990 commented on Cryptocurrency Management/ViewController.swift
> +        bt.titleLabel?.font = UIFont.systemFont(ofSize: 14)
修正しました。

2021-01-22 04:44 UTC, YukiT1990 commented on Cryptocurrency Management/ViewController.swift
>          bt.frame = CGRect(x: 261, y: 76, width: 120, height: 36)
修正しました。

2021-01-22 04:45 UTC, YukiT1990 commented on Cryptocurrency Management/ViewController.swift
> +        bt.frame = CGRect(x: 16, y: 76, width: 48, height: 48)
修正したらボタンが四角になったので元に戻しました。

2021-01-22 04:45 UTC, YukiT1990 commented on Cryptocurrency Management/ViewController.swift
> +        bt.layer.cornerRadius = bt.frame.height * 0.50
修正しました。

2021-01-22 04:50 UTC, YukiT1990 commented on Cryptocurrency Management/ViewController.swift
> +    private func layout() {
修正しました。

2021-01-22 05:14 UTC, YukiT1990 commented on Cryptocurrency Management/ViewController.swift
> +        cell.textLabel?.text = registeredCurrencies[indexPath.row].name
追加しました。とりあえずdefault imageを表示してあります。

2021-01-22 05:24 UTC, YukiT1990 commented on Cryptocurrency Management/ViewController.swift
> +        if allowDissmissModal == true {
修正しました。

2021-01-22 05:25 UTC, YukiT1990 commented on Cryptocurrency Management/ViewController.swift
> +        if tableViewEditingMode == true {
修正しました。

2021-01-22 05:30 UTC, YukiT1990 commented on Cryptocurrency Management/ViewController.swift
> +            allCurrencyLabel.leadingAnchor.constraint(equalTo: popupView.leadingAnchor, constant: 18)
viewDidLoad()内からsetupLayout()内に移動しました。

2021-01-22 05:30 UTC, YukiT1990 commented on Cryptocurrency Management/ViewController.swift
>          view.backgroundColor = UIColor(hex: "#010A43")
viewDidLoad()内からsetupLayout()内に移動しました。

2021-01-22 13:08 UTC, YukiT1990 commented on Cryptocurrency Management/ViewController.swift
> +        bt.setTitleColor(UIColor(hex: "#fc0303"), for: .normal)
stackViewに入れました。

2021-01-22 13:14 UTC, YukiT1990 commented on Cryptocurrency Management/ViewController.swift
>          bt.backgroundColor = UIColor(hex: "#212A6B", alpha: 1.0)
追加しました。

2021-01-22 13:16 UTC, YukiT1990 commented on Cryptocurrency Management/ViewController.swift
> +            allCurrencyLabel.leadingAnchor.constraint(equalTo: popupView.leadingAnchor, constant: 18)
stack viewに入れて削除しました。

2021-01-22 13:30 UTC, YukiT1990 commented on Cryptocurrency Management/ViewController.swift
>              addCurrencyButton.topAnchor.constraint(greaterThanOrEqualTo: view.safeAreaLayoutGuide.topAnchor, constant: 80),
popupView.addSubview(editButton)
popupView.addSubview(deleteButton)
popupView.addSubview(allCurrencyLabel)
を消去して
tableHeaderSV.topAnchor.constraint(equalTo: popupView.safeAreaLayoutGuide.topAnchor, constant: 15)
tableHeaderSV.heightAnchor.constraint(equalTo: headerWrapper.heightAnchor, multiplier: 0.7)
を追加しました。

2021-01-22 13:33 UTC, YukiT1990 commented on Cryptocurrency Management/ViewController.swift
> +        popupView.backgroundColor = UIColor(hex: "#10194E")
修正しました。

2021-01-22 13:34 UTC, YukiT1990 commented on Cryptocurrency Management/ViewController.swift
> +        popupView.addSubview(currencyTableView)
addSubviewはsetupLayout()内にまとめました。

2021-01-22 13:46 UTC, YukiT1990 commented on Cryptocurrency Management/ViewController.swift
> +        allowDissmissModal = tableViewEditingMode
修正しました。

2021-01-22 14:05 UTC, YukiT1990 commented on Cryptocurrency Management/ViewController.swift
> +        currencyTableView.trailingAnchor.constraint(equalTo: popupView.trailingAnchor).isActive = true
constraintsの設定をsetupLayout()のNSLayoutConstraint.activate内にまとめました。

2021-01-22 21:44 UTC, YukiT1990 commented on Cryptocurrency Management/ViewController.swift
> +            addCurrencyButton.heightAnchor.constraint(equalToConstant: 36),
削除するとaddCurrencyButtonが左に寄ってtableViewSwitchButtonと重なるので残してあります。

2021-01-22 21:49 UTC, YukiT1990 commented on Cryptocurrency Management/ViewController.swift
> +            tableViewSwitchButton.leadingAnchor.constraint(greaterThanOrEqualTo: view.safeAreaLayoutGuide.leadingAnchor, constant: 16),
tableViewSwitchButton.topAnchor.constraint(greaterThanOrEqualTo: view.safeAreaLayoutGuide.topAnchor, constant: 74)
は削除しましたが
tableViewSwitchButton.leadingAnchor.constraint(greaterThanOrEqualTo: view.safeAreaLayoutGuide.leadingAnchor, constant: 16)
を削除すると左に寄りすぎるので残してあります。

2021-01-22 22:40 UTC, YukiT1990 commented
確認お願いします。修正の詳細は各コメントに返信してあります。

2021-01-22 22:57 UTC, DaiSugi01 commented on Cryptocurrency Management/ViewController.swift
> +        bt.frame = CGRect(x: 16, y: 76, width: 48, height: 48)
すみません。raiusをheightで計算するように書いていると思うので、widthではなくheightでやってみてください
`bt.frame.size.height = 48`

2021-01-22 23:29 UTC, DaiSugi01 commented on Cryptocurrency Management/ViewController.swift
> +            addCurrencyButton.heightAnchor.constraint(equalToConstant: 36),
自分のローカルで動いたので、以下の部分を修正してたら動きますか？
あと追加依頼で申し訳ないですがHello Daikiの部分消しちゃいましょう。
（名前の長さによっては省略（....みたいに）されてしまう可能性があるので）

1. rootHeaderWrapperを削除（不要なので）
2. rootHeaderSVのalignment等を変更
```
sv.distribution = .equalSpacing
sv.alignment = .fill
```
3. 以下を変更
```
-        rootHeaderWrapper.addSubview(rootHeaderSV)
-        rootHeaderSV.addSubview(tableViewSwitchButton)
-        rootHeaderSV.addSubview(helloLabel)
-        rootHeaderSV.addSubview(addCurrencyButton)

↓

+        rootHeaderSV.addArrangedSubview(tableViewSwitchButton)
+        rootHeaderSV.addArrangedSubview(addCurrencyButton)
```

4. 以下のconstraintsを変更
```
-            rootHeaderWrapper.heightAnchor.constraint(equalToConstant: 50),
-            rootHeaderWrapper.topAnchor.constraint(equalTo: view.safeAreaLayoutGuide.topAnchor, constant: 20),
-            rootHeaderWrapper.leadingAnchor.constraint(equalTo: view.safeAreaLayoutGuide.leadingAnchor, constant: 10),
-            rootHeaderWrapper.trailingAnchor.constraint(equalTo: view.safeAreaLayoutGuide.trailingAnchor, constant: -10),

↓

+            rootHeaderSV.heightAnchor.constraint(equalToConstant: 50),
+            rootHeaderSV.topAnchor.constraint(equalTo: view.safeAreaLayoutGuide.topAnchor, constant: 20),
+            rootHeaderSV.leadingAnchor.constraint(equalTo: view.safeAreaLayoutGuide.leadingAnchor, constant: 10),
+            rootHeaderSV.trailingAnchor.constraint(equalTo: view.safeAreaLayoutGuide.trailingAnchor, constant: -10),
```

5.　以下を削除
```
-            rootHeaderSV.topAnchor.constraint(equalTo: rootHeaderWrapper.topAnchor),
-            rootHeaderSV.bottomAnchor.constraint(equalTo: rootHeaderWrapper.bottomAnchor),
-            rootHeaderSV.leadingAnchor.constraint(equalTo: rootHeaderWrapper.leadingAnchor),
-            rootHeaderSV.trailingAnchor.constraint(equalTo: rootHeaderWrapper.trailingAnchor),
-            helloLabel.topAnchor.constraint(equalTo: rootHeaderSV.safeAreaLayoutGuide.topAnchor, constant: 10),
-            helloLabel.leadingAnchor.constraint(greaterThanOrEqualTo: tableViewSwitchButton.trailingAnchor, constant:
-  10),
 -            addCurrencyButton.topAnchor.constraint(equalTo: rootHeaderSV.safeAreaLayoutGuide.topAnchor, constant: 6),
-            addCurrencyButton.trailingAnchor.constraint(equalTo: rootHeaderSV.safeAreaLayoutGuide.trailingAnchor, constant: -20),
-            addCurrencyButton.heightAnchor.constraint(equalToConstant: 36),
```

2021-01-23 03:47 UTC, YukiT1990 commented on Cryptocurrency Management/ViewController.swift
> +        bt.frame = CGRect(x: 16, y: 76, width: 48, height: 48)
bt.frame.size.height = 48で上手くいきました。

2021-01-23 04:08 UTC, YukiT1990 commented on Cryptocurrency Management/ViewController.swift
> +            addCurrencyButton.heightAnchor.constraint(equalToConstant: 36),
動きました。
Hello Daikiの部分削除しました。

2021-01-23 04:11 UTC, YukiT1990 commented
修正２か所とも上手くいきました。確認お願いします。

2021-01-23 08:11 UTC, DaiSugi01 approved these changes

2021-01-23 08:11 UTC, merged